name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/LICENSE'
      - '**/README.md'
      - '**/build.yml'
      - '**/.gitignore'
      - '**/.gitattributes'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            7.0.x
            8.0.x

      - name: Pin SDK to 8.0
        run: |
          echo '{"sdk":{"version":"8.0.0","rollForward":"latestFeature"}}' > global.json

      - name: Dotnet Restore
        run: dotnet restore

      - name: Build .Net7
        run: dotnet publish AssetStudio.GUI/AssetStudio.GUI.csproj -c Release -f net7.0-windows --no-self-contained

      - name: Build .Net8
        run: dotnet publish AssetStudio.GUI/AssetStudio.GUI.csproj -c Release -f net8.0-windows --no-self-contained

      - name: Build .Net7 CLI
        run: dotnet publish AssetStudio.CLI/AssetStudio.CLI.csproj -c Release -f net7.0-windows --no-self-contained

      - name: Build .Net8 CLI
        run: dotnet publish AssetStudio.CLI/AssetStudio.CLI.csproj -c Release -f net8.0-windows --no-self-contained

      - name: Upload .Net7 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net7.0-${{ github.sha }}
          path: AssetStudio.GUI/bin/Release/net7.0-windows/publish

      - name: Upload .Net8 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net8.0-${{ github.sha }}
          path: AssetStudio.GUI/bin/Release/net8.0-windows/publish

      - name: Upload .Net7 CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net7.0-cli-${{ github.sha }}
          path: AssetStudio.CLI/bin/Release/net7.0-windows/publish

      - name: Upload .Net8 CLI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net8.0-cli-${{ github.sha }}
          path: AssetStudio.CLI/bin/Release/net8.0-windows/publish
